Feature/15 model spec
Ryogo-Sasaki/sample_app_for_rspec pull request #2
Opened 2020-03-04 01:10 UTC by Ryogo-Sasaki

2020-03-04 03:17 UTC, yuji91 commented
`it 'is invalid with a duplicate title'`のテストケースについて、下記3点を整理してみてください。
・確認対象（のValidation）は何か
・どのような状況でテスト成功（invalidであることの確認ができる）となるのか
・テストケースを満たすためのテストデータは何が必要か

2020-03-04 09:45 UTC, Ryogo-Sasaki commented
・確認対象（のValidation）は何か
→model(task)のuniqueness: true
・どのような状況でテスト成功（invalidであることの確認ができる）となるのか
→➃it 'is invalid with a duplicate title' do end

![スクリーンショット 2020-03-04 12 01 54](https://user-images.githubusercontent.com/39234808/75866375-4cf4f680-5e48-11ea-9b56-c2f9ef1a7481.png)

・テストケースを満たすためのテストデータは何が必要か

2020-03-05 04:15 UTC, Ryogo-Sasaki commented
## ➃it 'is invalid with a duplicate title' do end
![スクリーンショット 2020-03-05 12 26 04](https://user-images.githubusercontent.com/39234808/75947309-410a4280-5ee3-11ea-91b8-7f5b472fe36d.png)

## ➄it 'is valid with another title' do end
![スクリーンショット 2020-03-05 12 25 38](https://user-images.githubusercontent.com/39234808/75947321-4a93aa80-5ee3-11ea-9f97-09de537d3591.png)

2020-03-05 04:27 UTC, yuji91 commented on spec/models/task_spec.rb
> +    @task.valid?
Viewに表示する訳ではないので、インスタンス変数ではなくローカル変数で十分である点については注意してください。
なぜ`@task`にしなければならないのか、という点を普段の他の実装をする時にも意識できると良いです。

2020-03-05 04:29 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task.errors[:title]).to be_valid
エラーメッセージの確認も行なっておきましょう。
現状では「バリデーションエラーが起こること」の確認しかできて出来ていないため、バリデーションが複数件設定されていた場合に「どのバリデーション項目のエラーを確認しているのか」はメッセージ確認で担保されます。

2020-03-05 04:31 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task.errors[:title]).to be_valid
`expect(task.errors[:title]).to be_valid`では何がどうなることを確認していますか？

また、このテストケースで確認することは何かを改めて整理して欲しいです。

2020-03-05 04:32 UTC, yuji91 requested changes
定義しているテストデータの内容については問題ありません。
指摘事項の対応をお願いします。

2020-03-05 04:34 UTC, Ryogo-Sasaki commented on spec/models/task_spec.rb
> +    @task.valid?
インスタンス変数で書いていたのは、taskを作っていることをより明示的にするためでしたが、仰る通りローカル変数だけで十分でしたね、、。

2020-03-05 05:29 UTC, Ryogo-Sasaki commented on spec/models/task_spec.rb
> +    @task.valid?
4816f39  にて修正しました！

2020-03-05 05:29 UTC, Ryogo-Sasaki commented on spec/models/task_spec.rb
> +    expect(task.errors[:title]).to be_valid
f9ff629  にて修正しました！

2020-03-05 05:32 UTC, Ryogo-Sasaki commented on spec/models/task_spec.rb
> +    expect(task.errors[:title]).to be_valid
expect(task.errors[:title]).to be_validで、タイトルが複数あった時、task.valid?がfalseになることを確認しております。(uniqueness true)

2020-03-05 05:35 UTC, Ryogo-Sasaki commented
## テストケースで確認していること

2020-03-05 05:48 UTC, yuji91 commented on spec/models/task_spec.rb
> +  it 'タイトルが重複していたらinvalid' do
`➄it 'is valid with another title'`に対して適切な説明ではないので修正をお願いします。
（➃と同じままになっている）

2020-03-05 05:49 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task).to be_valid
`be_valid`マッチャーは内部で`valid`の判定を行なっているので`task.valid?`の記載が不要であることを確認してください。

2020-03-05 05:52 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task.errors[:title]).to be_valid, include("can't be blank")
`task.errors[:title]`に対して`be_valid`マッチャを実行していますが、errorsで取得したオブジェクトではなく、テストデータであるtaskオブジェクト自体を判定してください。
また、expectで複数の内容を確認するとテスト失敗時に何が原因で失敗したかが読み取りづらいため、確認観点ごとにexpectを増やした方が分かりやすいと思います。

2020-03-05 05:52 UTC, yuji91 requested changes
コメントしました！

2020-03-05 06:04 UTC, Ryogo-Sasaki commented on spec/models/task_spec.rb
> +  it 'タイトルが重複していたらinvalid' do
37bd8ca  にて修正しました！

2020-03-05 06:04 UTC, Ryogo-Sasaki commented on spec/models/task_spec.rb
> +    expect(task).to be_valid
048b5c3  にて修正しました！

2020-03-05 06:04 UTC, Ryogo-Sasaki commented on spec/models/task_spec.rb
> +    expect(task.errors[:title]).to be_valid, include("can't be blank")
9b6a6ca  にて修正しました！

2020-03-05 06:16 UTC, yuji91 commented on spec/models/task_spec.rb
> +    )
この`Task.create`する部分は`FactoryBot`を使って書いてみましょう！

2020-03-05 06:17 UTC, yuji91 requested changes
テストの内容自体はOKだと思います。

➃と➄について`FactoryBot`を利用してみましょう！
https://github.com/thoughtbot/factory_bot_rails

2020-03-05 11:05 UTC, yuji91 commented on spec/models/task_spec.rb
> +    task = Task.new(title: 'aaa', status: '')
存在しないという場合の表現を空文字にするのかnilを代入するのかは少し気にした方がいいですが、特に修正しなくて大丈夫です！

2020-03-05 11:09 UTC, yuji91 commented on spec/factories/tasks.rb
> +    status {:doing}
`{ :doing }`とブレース（波括弧）の中の値は半角スペース入れた方が見やすいですが、次の課題で直しても大丈夫です！

2020-03-05 11:10 UTC, yuji91 approved these changes
LGTMです！
次のSystemSpecとオプション課題がテストの山場なので引き続き頑張ってください！

2020-03-05 11:17 UTC, merged